version: '3.6'
services:
    api:
        container_name: api
        restart: always
        build: .
        ports:
            - 9000:9000
        env_file: .env
        depends_on:
            - db
        volumes:
            - .:/bandlabs-assesment-imagegram

    db:
        container_name: postgres
        image: postgres:13.1
        ports:
            - '5433:${DB_PORT}'
        volumes:
            - data:/data/db
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER:${DB_USER}
volumes:
    data:
